import forecast from "@/lev/forecast.json";

/**
 * The single source of truth for every number the site displays.
 *
 * Before this file existed, "28" was hardcoded in three places
 * (HeroCountdown.tsx, Hero.tsx's sr-only span, and the methodology copy),
 * so changing the countdown meant changing three files and hoping.
 * Now it comes from lev/forecast.json, which is generated by
 * `npx tsx lev/run.ts --write` and regenerated in CI.
 *
 * ─── TO SWITCH THE HEADLINE NUMBER, CHANGE THIS ONE LINE ───
 *   "model"  → the computed median from lev/params.json (currently 2092)
 *   "legacy" → the original hand-set 28-year placeholder
 */
export const COUNTDOWN_SOURCE: "model" | "legacy" = "model";

const LEGACY_YEARS = 28;

const round = (v: number | null) => (v === null ? null : Math.round(v));

const modelYears = round(forecast.years.p50) ?? LEGACY_YEARS;

export const countdown = {
  /** Big number in the hero. */
  years: COUNTDOWN_SOURCE === "model" ? modelYears : LEGACY_YEARS,
  /** True when the headline is computed rather than hand-set. */
  isComputed: COUNTDOWN_SOURCE === "model",

  baseYear: forecast.baseYear,
  medianYear: forecast.calendarYears.p50,
  earlyYear: forecast.calendarYears.p10,
  lateYear: forecast.calendarYears.p90,

  /** Healthy years gained per calendar year, today. LEV needs 1.0. */
  currentGain: forecast.currentGain,
  levThreshold: 1,
  /** Share of simulations that reach LEV at all, inside the horizon. */
  probabilityReached: forecast.probabilityReached,

  modelId: forecast.modelId,
  paramsVersion: forecast.paramsVersion,
  draws: forecast.draws,
  seed: forecast.seed,
} as const;

/** P(LEV reached by `year`), 0–1. Returns null outside the modelled horizon. */
export function probabilityBy(year: number): number | null {
  const row = forecast.cumulative.find((c) => c.year === year);
  return row ? row.probability : null;
}

export const trajectory = forecast.trajectory;
export const cumulative = forecast.cumulative;

export const formatPercent = (v: number) => `${Math.round(v * 100)}%`;
